version: "3.9"
name: 2bttns-docker-compose
services:
  twobttns:
    image: 2bttns/2bttns
    container_name: 2bttns
    ports:
      - 3262:3262
    environment:
      DATABASE_URL: postgresql://username:password@db-hostname:5432/db
      NEXTAUTH_SECRET: 2ad12708e5b8213c52480389f6a7851d5f2d6cffaf781fe4e07ed2b7670fd3ed
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db-hostname
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: null
